NAME	= braiiinz

CC		= c++
CFLAGS	= -Wall -Wextra -Werror -std=c++98

SRC		= Zombie.cpp main.cpp newZombie.cpp randomChump.cpp
HEADERS	= Zombie.hpp
OBJ		= $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

%.o : %.cpp $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@

clean: 
	rm -rf $(OBJ)

fclean: clean
	rm -rf $(NAME)

re: fclean all